# Generated by Django 5.0.4 on 2024-05-25 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priority', models.CharField(default='Moderate', max_length=50)),
                ('risk_level', models.CharField(default='low', max_length=50)),
                ('control_measures_effectiveness', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance'), ('Inactive', 'Inactive')], default='Active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_question_1', models.CharField(choices=[('birth_place', 'What is the name of the town where you were born?'), ('sibling_name', "What is your oldest sibling's middle name?"), ('first_school', 'What is the name of the school you attended?')], max_length=255)),
                ('security_answer_1', models.CharField(max_length=255)),
                ('security_question_2', models.CharField(choices=[('parents_city', 'In what city did your parents meet?'), ('first_car', 'What was the make and model of your first car?'), ('first_concert', 'What was the first concert you attended?')], max_length=255)),
                ('security_answer_2', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
